/**
 * Regenerates lib/waitlist/plz-data.ts — the directory of real German
 * delivery postal codes the waitlist form validates against.
 *
 *   npm run plz:update                 # download GeoNames DE.zip and rebuild
 *   npm run plz:update -- path/DE.txt  # rebuild from an already extracted file
 *
 * Source: https://download.geonames.org/export/zip/DE.zip (CC BY 4.0).
 * Rows whose admin1 code is not a two-letter state code (BY, NW, …) are
 * Großempfänger/PO-box codes assigned to single companies (e.g. 12345 =
 * Krankenhaus Neukölln) — no one lives there, so they are excluded.
 *
 * Needs the `unzip` CLI when downloading (macOS/Linux have it built in).
 */

import { execFileSync } from "child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "fs";
import { tmpdir } from "os";
import path from "path";

const GEONAMES_URL = "https://download.geonames.org/export/zip/DE.zip";
const OUT_FILE = path.join(__dirname, "..", "lib", "waitlist", "plz-data.ts");

// Real delivery PLZs must stay accepted, known garbage must stay rejected —
// if the source data ever breaks one of these, refuse to write the file.
const MUST_EXIST = ["97688", "97616", "10115", "20095", "80331", "01067", "99998"];
const MUST_NOT_EXIST = ["11111", "12345", "00000", "99999"];
const EXPECTED_COUNT_RANGE = [7500, 9500] as const;

async function loadRawTsv(): Promise<string> {
  const localFile = process.argv[2];
  if (localFile) return readFileSync(localFile, "utf8");

  console.log(`Downloading ${GEONAMES_URL} …`);
  const res = await fetch(GEONAMES_URL);
  if (!res.ok) throw new Error(`Download failed: HTTP ${res.status}`);

  const dir = mkdtempSync(path.join(tmpdir(), "plz-"));
  try {
    const zipFile = path.join(dir, "DE.zip");
    writeFileSync(zipFile, Buffer.from(await res.arrayBuffer()));
    return execFileSync("unzip", ["-p", zipFile, "DE.txt"], {
      encoding: "utf8",
      maxBuffer: 64 * 1024 * 1024,
    });
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

async function main() {
  const rows = (await loadRawTsv()).split("\n");

  const plzs = new Set<number>();
  for (const row of rows) {
    const cols = row.split("\t");
    const plz = cols[1];
    const admin1 = cols[4];
    if (!plz || !/^\d{5}$/.test(plz)) continue;
    if (!admin1 || !/^[A-Z]{2}$/.test(admin1)) continue; // Großempfänger etc.
    plzs.add(Number(plz));
  }

  if (plzs.size < EXPECTED_COUNT_RANGE[0] || plzs.size > EXPECTED_COUNT_RANGE[1]) {
    throw new Error(`Implausible PLZ count ${plzs.size} — source format changed?`);
  }
  for (const plz of MUST_EXIST) {
    if (!plzs.has(Number(plz))) throw new Error(`Sanity check failed: ${plz} missing`);
  }
  for (const plz of MUST_NOT_EXIST) {
    if (plzs.has(Number(plz))) throw new Error(`Sanity check failed: ${plz} present`);
  }

  // 100 000 possible codes → 12.5 KB bitmask, O(1) lookup on both ends.
  const bitmask = new Uint8Array(100_000 / 8);
  for (const plz of plzs) bitmask[plz >> 3] |= 1 << (plz & 7);
  const b64 = Buffer.from(bitmask).toString("base64");

  const generatedAt = new Date().toISOString().slice(0, 10);
  const source = process.argv[2] ? `local file (GeoNames DE.txt)` : GEONAMES_URL;
  writeFileSync(
    OUT_FILE,
    `/**
 * AUTO-GENERATED by scripts/generate-plz-data.ts — do not edit by hand.
 * Refresh with: npm run plz:update
 *
 * All ${plzs.size} German delivery postal codes (Großempfänger/PO-box codes
 * excluded) as a 100 000-bit bitmask.
 * Source: ${source} (CC BY 4.0), generated ${generatedAt}.
 *
 * Isomorphic on purpose: imported by the browser form and the API route.
 */

export const PLZ_COUNT = ${plzs.size};

const PLZ_BITMASK_B64 =
  "${b64}";

let bits: Uint8Array | null = null;

function bitmask(): Uint8Array {
  if (!bits) {
    bits =
      typeof Buffer !== "undefined"
        ? new Uint8Array(Buffer.from(PLZ_BITMASK_B64, "base64"))
        : Uint8Array.from(atob(PLZ_BITMASK_B64), (c) => c.charCodeAt(0));
  }
  return bits;
}

/** True when the (already format-checked) 5-digit code is a real German delivery PLZ. */
export function isRealGermanPlz(plz: string): boolean {
  if (!/^\\d{5}$/.test(plz)) return false;
  const n = Number(plz);
  return (bitmask()[n >> 3]! & (1 << (n & 7))) !== 0;
}
`,
  );

  console.log(`Wrote ${path.relative(process.cwd(), OUT_FILE)} with ${plzs.size} PLZs.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
